version: '3.8'
services:
  order-ui:
    build: .
    container_name: order-rest
    ports:
      - "8999:80"
    restart: always

  caddy:
    image: caddy:2
    container_name: order-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
